const FETCH_PHOTOS = "FETCH_PHOTOS";
const ADD_PHOTO = "ADD_PHOTO";
const DELETE_PHOTO = "DELETE_PHOTO";
const TOGGLE_ADD_PHOTO = "TOGGLE_ADD_PHOTO";
const TOGGLE_DELETE_PHOTO = "TOGGLE_DELETE_PHOTO";
const GET_PHOTO_ID = "GET_PHOTO_ID";

export {
  FETCH_PHOTOS,
  ADD_PHOTO,
  DELETE_PHOTO,
  TOGGLE_ADD_PHOTO,
  TOGGLE_DELETE_PHOTO,
  GET_PHOTO_ID,
};
